import { ChainConfig } from "../../common/interfaces";
import { $, toJson } from "./config-utils";

export type NetworkName = "NEUTRON";
export type Wasm = "staking.wasm" | "voter.wasm";
export type Label = "staking" | "voter";

export const ADDRESS = {
  WORKER: "",
};

/**
 * This config is used to generate `config.json` used by any script (ts, js, bash).
 * It must be filled manually. If any contract must be added it's required to include
 * it with default parameters - code is 0, address is "".
 * This config uses logs.json generated by local-interchaintest to update endpoints
 * in cofig.json.
 */
export const CHAIN_CONFIG: ChainConfig = {
  CHAINS: [
    {
      NAME: "neutron",
      PREFIX: "neutron",
      OPTIONS: [
        {
          TYPE: "main",
          DENOM: "untrn",
          CHAIN_ID: "neutron-1",
          RPC_LIST: ["https://rpc.cosmos.directory/neutron"],
          GAS_PRICE_AMOUNT: 0.0053,
          STORE_CODE_GAS_MULTIPLIER: 21.5,
          CONTRACTS: [
            {
              WASM: "staking.wasm",
              LABEL: "staking",
              INIT_MSG: toJson({}),
              MIGRATE_MSG: toJson({}),
              UPDATE_MSG: toJson({}),
              CODE: 0,
              ADDRESS:
                "neutron19q93n64nyet24ynvw04qjqmejffkmyxakdvl08sf3n3yeyr92lrs2makhx",
            },

            {
              WASM: "voter.wasm",
              LABEL: "voter",
              INIT_MSG: toJson({}),
              MIGRATE_MSG: toJson({}),
              UPDATE_MSG: toJson({}),
              CODE: 0,
              ADDRESS:
                "neutron13l5nw6fh4xascjfyru5pe9w5ur8rp7svzl7hhkdh7jfdk3fup75quz9zy5",
            },
          ],
          IBC: [],
        },
      ],
    },
  ],
};
